const APP_CONFIG = {
  pageTitle: "\u00BFYo te amo mas?",
  eyebrow: "Pregunta importante",
  question: "\u00BFYo te amo mas?",
  supportText: "Piensalo bien antes de responder.",
  yesText: "Si",
  noText: "No",
  successTitle: "Yo sabia",
  successMessage: "Entonces gano yo. Te amo demasiado.",
  musicButtonPlay: "\u266B",
  musicButtonPause: "||",
  backgroundImage: "fondo.png",
  iconImage: "icono.gif",
  musicFile: "musica.mp3",
  overlayOpacity: 0.34,
  cardBlur: 18,
  cardRoundness: 38,
  noButtonDangerZone: 240,
  noButtonPadding: 16,
  autoPlayMusic: false,
};
